name: Tests
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Create mocks
        run: dart run build_runner build

      - name: Run Tests
        run: flutter test

# Commented out because it's resource heavy
#      - name: Build APK
#        run: flutter build apk
#
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: app-release
#          path: build/app/outputs/apk/release/
